/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    GoTop: typeof import('./src/components/GoTop/GoTop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNavigateBar: typeof import('./src/components/TopNavigateBar/TopNavigateBar.vue')['default']
  }
}
